### ISSUE TITLE
Feature Request: Flash Flashlight in pattern

### ISSUE THREAD

**Issue by BoBeR182** [whyrising/flashy-alarm#30]
Can you please create a feature to have the flashlight strobe or flash on and off in a customizable pattern.

**Comment by whyrising** [comment]
> Can you please create a feature to have the flashlight strobe or flash on and off in a customizable pattern.

I'll see what I can do, thanks.

**Comment by whyrising** [comment]
This feature has been implemented and It will be available next release. You can check it out in README.
I'm going to close this for now, cheers.
