### ISSUE TITLE
Flashlight does not turn off with alarm

### ISSUE THREAD

**Issue by BoBeR182** [whyrising/flashy-alarm#31]
Flashlight is left on after alarm is dismissed or silenced.

**Comment by whyrising** [comment]
> Flashlight is left on after alarm is dismissed or silenced.

Hi, thanks for using the app.
About your issue, It is not a bug. I never intended to turn it off in the first place.

**Comment by whyrising** [comment]
The flashlight is off now when you dismiss or snooze the alarm. It will be available next release.
