### ISSUE TITLE
LineageOS Default Clock App Compatibility

### ISSUE THREAD

**Issue by Lovebird-Connoisseur** [whyrising/flashy-alarm#36]
Hello!

I came accross your app on fdroid yesterday, I noticed the description mentioned it currently only worked with the Samsung alarm app, nevertheless I decided to give it a quick try to see if it worked on my device.

And even though I don't use Samsungs alarm app, I'm happy to confirm that it worked with my device!

Currently I'm using LineageOS for microG on a Redmi Note 7 (Android 11), with the stock clock/alarm app.

**Comment by whyrising** [comment]
Hello there!

Thank you very much for your feedback. Glad to hear it worked for you.

I already reimplemented the things that made me doubt the app would work on other devices. I'd love to hear your feedback again when the next version is released. 
The goal of this release is to make the app even more straightforward to use (only one tap to enable/disable).

Kind regards.
